image: gcc

build:
  stage: build

  script:
  - mkdir build
  - cd build
  - . ../ci/use-clang.sh
  - cmake -DwexBUILD_SHARED=ON ..
  - make

  artifacts:
    paths:
    - build/syncped.app/Contents/MacOS/syncped

test:
  stage: test
  script:
  - cd test
  - robot *.robot
