image: gcc

build:
  stage: build

  script:
  - wex-build-gen.sh

  artifacts:
    paths:
    - build/src/syncped.app/Contents/MacOS/syncped

test:
  stage: test
  script:
  - cd test
  - robot *.robot
