# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: gcc
build:
  stage: build
  script:
  - g++ helloworld.cpp -o mybinary
  artifacts:
    paths:
    - mybinary
test:
  stage: test
  script:
  - "./runmytests.sh"
stages:
- test
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
