image: gcc

build:
  stage: build

  script:
  - export PATH=/usr/local/Cellar/homebrew/opt/bison/bin:/usr/local/Cellar/homebrew/bin:/usr/local/bin:$PATH
  - zsh
  - wex-build-gen.sh

  artifacts:
    paths:
    - build/src/syncped.app/Contents/MacOS/syncped

test:
  stage: test

  script:
  - export PATH=/usr/local/Cellar/homebrew/opt/bison/bin:/usr/local/Cellar/homebrew/bin:/usr/local/bin:$PATH
  - cd test
  - robot *.robot
